<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        DB::table('countries')->truncate();

        $countries = [
            ['name' => 'Afghanistan', 'code' => '+93', 'currency' => 'Afghan Afghani', 'iso2' => 'AF'],
            ['name' => 'Albania', 'code' => '+355', 'currency' => 'Albanian Lek', 'iso2' => 'AL'],
            ['name' => 'Algeria', 'code' => '+213', 'currency' => 'Algerian Dinar', 'iso2' => 'DZ'],
            ['name' => 'Andorra', 'code' => '+376', 'currency' => 'Euro', 'iso2' => 'AD'],
            ['name' => 'Angola', 'code' => '+244', 'currency' => 'Angolan Kwanza', 'iso2' => 'AO'],
            ['name' => 'Argentina', 'code' => '+54', 'currency' => 'Argentine Peso', 'iso2' => 'AR'],
            ['name' => 'Armenia', 'code' => '+374', 'currency' => 'Armenian Dram', 'iso2' => 'AM'],
            ['name' => 'Australia', 'code' => '+61', 'currency' => 'Australian Dollar', 'iso2' => 'AU'],
            ['name' => 'Austria', 'code' => '+43', 'currency' => 'Euro', 'iso2' => 'AT'],
            ['name' => 'Azerbaijan', 'code' => '+994', 'currency' => 'Azerbaijani Manat', 'iso2' => 'AZ'],
            ['name' => 'Bahamas', 'code' => '+1 242', 'currency' => 'Bahamian Dollar', 'iso2' => 'BS'],
            ['name' => 'Bahrain', 'code' => '+973', 'currency' => 'Bahraini Dinar', 'iso2' => 'BH'],
            ['name' => 'Bangladesh', 'code' => '+880', 'currency' => 'Bangladeshi Taka', 'iso2' => 'BD'],
            ['name' => 'Barbados', 'code' => '+1 246', 'currency' => 'Barbadian Dollar', 'iso2' => 'BB'],
            ['name' => 'Belarus', 'code' => '+375', 'currency' => 'Belarusian Ruble', 'iso2' => 'BY'],
            ['name' => 'Belgium', 'code' => '+32', 'currency' => 'Euro', 'iso2' => 'BE'],
            ['name' => 'Belize', 'code' => '+501', 'currency' => 'Belize Dollar', 'iso2' => 'BZ'],
            ['name' => 'Benin', 'code' => '+229', 'currency' => 'West African CFA franc', 'iso2' => 'BJ'],
            ['name' => 'Bermuda', 'code' => '+1 441', 'currency' => 'Bermudian Dollar', 'iso2' => 'BM'],
            ['name' => 'Bhutan', 'code' => '+975', 'currency' => 'Bhutanese Ngultrum', 'iso2' => 'BT'],
            ['name' => 'Bolivia', 'code' => '+591', 'currency' => 'Bolivian Boliviano', 'iso2' => 'BO'],
            ['name' => 'Bosnia and Herzegovina', 'code' => '+387', 'currency' => 'Bosnia and Herzegovina Convertible Mark', 'iso2' => 'BA'],
            ['name' => 'Botswana', 'code' => '+267', 'currency' => 'Botswana Pula', 'iso2' => 'BW'],
            ['name' => 'Bouvet Island', 'code' => '+47', 'currency' => 'Norwegian Krone', 'iso2' => 'BV'],
            ['name' => 'Brazil', 'code' => '+55', 'currency' => 'Brazilian Real', 'iso2' => 'BR'],
            ['name' => 'British Indian Ocean Territory', 'code' => '+246', 'currency' => 'United States Dollar', 'iso2' => 'IO'],
            ['name' => 'Brunei Darussalam', 'code' => '+673', 'currency' => 'Brunei Dollar', 'iso2' => 'BN'],
            ['name' => 'Bulgaria', 'code' => '+359', 'currency' => 'Bulgarian Lev', 'iso2' => 'BG'],
            ['name' => 'Burkina Faso', 'code' => '+226', 'currency' => 'West African CFA franc', 'iso2' => 'BF'],
            ['name' => 'Burundi', 'code' => '+257', 'currency' => 'Burundian Franc', 'iso2' => 'BI'],
            ['name' => 'Cabo Verde', 'code' => '+238', 'currency' => 'Cape Verdean Escudo', 'iso2' => 'CV'],
            ['name' => 'Cambodia', 'code' => '+855', 'currency' => 'Cambodian Riel', 'iso2' => 'KH'],
            ['name' => 'Cameroon', 'code' => '+237', 'currency' => 'Central African CFA franc', 'iso2' => 'CM'],
            ['name' => 'Canada', 'code' => '+1', 'currency' => 'Canadian Dollar', 'iso2' => 'CA'],
            ['name' => 'Cayman Islands', 'code' => '+1 345', 'currency' => 'Cayman Islands Dollar', 'iso2' => 'KY'],
            ['name' => 'Central African Republic', 'code' => '+236', 'currency' => 'Central African CFA franc', 'iso2' => 'CF'],
            ['name' => 'Chad', 'code' => '+235', 'currency' => 'Central African CFA franc', 'iso2' => 'TD'],
            ['name' => 'Chile', 'code' => '+56', 'currency' => 'Chilean Peso', 'iso2' => 'CL'],
            ['name' => 'China', 'code' => '+86', 'currency' => 'Renminbi', 'iso2' => 'CN'],
            ['name' => 'Christmas Island', 'code' => '+61', 'currency' => 'Australian Dollar', 'iso2' => 'CX'],
            ['name' => 'Cocos (Keeling) Islands', 'code' => '+61', 'currency' => 'Australian Dollar', 'iso2' => 'CC'],
            ['name' => 'Colombia', 'code' => '+57', 'currency' => 'Colombian Peso', 'iso2' => 'CO'],
            ['name' => 'Comoros', 'code' => '+269', 'currency' => 'Comorian Franc', 'iso2' => 'KM'],
            ['name' => 'Congo (Congo-Brazzaville)', 'code' => '+242', 'currency' => 'Central African CFA franc', 'iso2' => 'CG'],
            ['name' => 'Congo (Democratic Republic) (Congo-Kinshasa)', 'code' => '+243', 'currency' => 'Congolese Franc', 'iso2' => 'CD'],
            ['name' => 'Cook Islands', 'code' => '+682', 'currency' => 'New Zealand Dollar', 'iso2' => 'CK'],
            ['name' => 'Costa Rica', 'code' => '+506', 'currency' => 'Costa Rican Colón', 'iso2' => 'CR'],
            ['name' => 'Croatia', 'code' => '+385', 'currency' => 'Croatian Kuna', 'iso2' => 'HR'],
            ['name' => 'Cuba', 'code' => '+53', 'currency' => 'Cuban Peso', 'iso2' => 'CU'],
            ['name' => 'Cura\u00e7ao', 'code' => '+599', 'currency' => 'Netherlands Antillean Guilder', 'iso2' => 'CW'],
            ['name' => 'Cyprus', 'code' => '+357', 'currency' => 'Euro', 'iso2' => 'CY'],
            ['name' => 'Czech Republic', 'code' => '+420', 'currency' => 'Czech Koruna', 'iso2' => 'CZ'],
            ['name' => 'Denmark', 'code' => '+45', 'currency' => 'Danish Krone', 'iso2' => 'DK'],
            ['name' => 'Djibouti', 'code' => '+253', 'currency' => 'Djiboutian Franc', 'iso2' => 'DJ'],
            ['name' => 'Dominica', 'code' => '+1 767', 'currency' => 'East Caribbean Dollar', 'iso2' => 'DM'],
            ['name' => 'Dominican Republic', 'code' => '+1 809', 'currency' => 'Dominican Peso', 'iso2' => 'DO'],
            ['name' => 'Ecuador', 'code' => '+593', 'currency' => 'United States Dollar', 'iso2' => 'EC'],
            ['name' => 'Egypt', 'code' => '+20', 'currency' => 'Egyptian Pound', 'iso2' => 'EG'],
            ['name' => 'El Salvador', 'code' => '+503', 'currency' => 'United States Dollar', 'iso2' => 'SV'],
            ['name' => 'Equatorial Guinea', 'code' => '+240', 'currency' => 'Central African CFA franc', 'iso2' => 'GQ'],
            ['name' => 'Eritrea', 'code' => '+291', 'currency' => 'Eritrean Nakfa', 'iso2' => 'ER'],
            ['name' => 'Estonia', 'code' => '+372', 'currency' => 'Euro', 'iso2' => 'EE'],
            ['name' => 'Eswatini', 'code' => '+268', 'currency' => 'Swazi Lilangeni', 'iso2' => 'SZ'],
            ['name' => 'Ethiopia', 'code' => '+251', 'currency' => 'Ethiopian Birr', 'iso2' => 'ET'],
            ['name' => 'Falkland Islands', 'code' => '+500', 'currency' => 'Falkland Islands Pound', 'iso2' => 'FK'],
            ['name' => 'Faroe Islands', 'code' => '+298', 'currency' => 'Danish Krone', 'iso2' => 'FO'],
            ['name' => 'Fiji', 'code' => '+679', 'currency' => 'Fijian Dollar', 'iso2' => 'FJ'],
            ['name' => 'Finland', 'code' => '+358', 'currency' => 'Euro', 'iso2' => 'FI'],
            ['name' => 'France', 'code' => '+33', 'currency' => 'Euro', 'iso2' => 'FR'],
            ['name' => 'French Guiana', 'code' => '+594', 'currency' => 'Euro', 'iso2' => 'GF'],
            ['name' => 'French Polynesia', 'code' => '+689', 'currency' => 'CFP Franc', 'iso2' => 'PF'],
            ['name' => 'French Southern and Antarctic Lands', 'code' => '+262', 'currency' => 'Euro', 'iso2' => 'TF'],
            ['name' => 'Gabon', 'code' => '+241', 'currency' => 'Central African CFA franc', 'iso2' => 'GA'],
            ['name' => 'Gambia', 'code' => '+220', 'currency' => 'Gambian Dalasi', 'iso2' => 'GM'],
            ['name' => 'Georgia', 'code' => '+995', 'currency' => 'Georgian Lari', 'iso2' => 'GE'],
            ['name' => 'Germany', 'code' => '+49', 'currency' => 'Euro', 'iso2' => 'DE'],
            ['name' => 'Ghana', 'code' => '+233', 'currency' => 'Ghanaian Cedi', 'iso2' => 'GH'],
            ['name' => 'Gibraltar', 'code' => '+350', 'currency' => 'Gibraltar Pound', 'iso2' => 'GI'],
            ['name' => 'Greece', 'code' => '+30', 'currency' => 'Euro', 'iso2' => 'GR'],
            ['name' => 'Greenland', 'code' => '+299', 'currency' => 'Danish Krone', 'iso2' => 'GL'],
            ['name' => 'Grenada', 'code' => '+1 473', 'currency' => 'East Caribbean Dollar', 'iso2' => 'GD'],
            ['name' => 'Guadeloupe', 'code' => '+590', 'currency' => 'Euro', 'iso2' => 'GP'],
            ['name' => 'Guam', 'code' => '+1 671', 'currency' => 'United States Dollar', 'iso2' => 'GU'],
            ['name' => 'Guatemala', 'code' => '+502', 'currency' => 'Guatemalan Quetzal', 'iso2' => 'GT'],
            ['name' => 'Guernsey', 'code' => '+44', 'currency' => 'British Pound Sterling', 'iso2' => 'GG'],
            ['name' => 'Guinea', 'code' => '+224', 'currency' => 'Guinean Franc', 'iso2' => 'GN'],
            ['name' => 'Guinea-Bissau', 'code' => '+245', 'currency' => 'West African CFA franc', 'iso2' => 'GW'],
            ['name' => 'Guyana', 'code' => '+592', 'currency' => 'Guyanese Dollar', 'iso2' => 'GY'],
            ['name' => 'Haiti', 'code' => '+509', 'currency' => 'Haitian Gourde', 'iso2' => 'HT'],
            ['name' => 'Heard Island and McDonald Islands', 'code' => '+0', 'currency' => 'Australian Dollar', 'iso2' => 'HM'],
            ['name' => 'Holy See', 'code' => '+379', 'currency' => 'Euro', 'iso2' => 'VA'],
            ['name' => 'Honduras', 'code' => '+504', 'currency' => 'Honduran Lempira', 'iso2' => 'HN'],
            ['name' => 'Hong Kong', 'code' => '+852', 'currency' => 'Hong Kong Dollar', 'iso2' => 'HK'],
            ['name' => 'Hungary', 'code' => '+36', 'currency' => 'Hungarian Forint', 'iso2' => 'HU'],
            ['name' => 'Iceland', 'code' => '+354', 'currency' => 'Icelandic Króna', 'iso2' => 'IS'],
            ['name' => 'India', 'code' => '+91', 'currency' => 'Indian Rupee', 'iso2' => 'IN'],
            ['name' => 'Indonesia', 'code' => '+62', 'currency' => 'Indonesian Rupiah', 'iso2' => 'ID'],
            ['name' => 'Iran', 'code' => '+98', 'currency' => 'Iranian Rial', 'iso2' => 'IR'],
            ['name' => 'Iraq', 'code' => '+964', 'currency' => 'Iraqi Dinar', 'iso2' => 'IQ'],
            ['name' => 'Ireland', 'code' => '+353', 'currency' => 'Euro', 'iso2' => 'IE'],
            ['name' => 'Isle of Man', 'code' => '+44', 'currency' => 'British Pound Sterling', 'iso2' => 'IM'],
            ['name' => 'Israel', 'code' => '+972', 'currency' => 'Israeli New Shekel', 'iso2' => 'IL'],
            ['name' => 'Italy', 'code' => '+39', 'currency' => 'Euro', 'iso2' => 'IT'],
            ['name' => 'Jamaica', 'code' => '+1 876', 'currency' => 'Jamaican Dollar', 'iso2' => 'JM'],
            ['name' => 'Japan', 'code' => '+81', 'currency' => 'Japanese Yen', 'iso2' => 'JP'],
            ['name' => 'Jersey', 'code' => '+44', 'currency' => 'British Pound Sterling', 'iso2' => 'JE'],
            ['name' => 'Jordan', 'code' => '+962', 'currency' => 'Jordanian Dinar', 'iso2' => 'JO'],
            ['name' => 'Kazakhstan', 'code' => '+7', 'currency' => 'Kazakhstani Tenge', 'iso2' => 'KZ'],
            ['name' => 'Kenya', 'code' => '+254', 'currency' => 'Kenyan Shilling', 'iso2' => 'KE'],
            ['name' => 'Kiribati', 'code' => '+686', 'currency' => 'Australian Dollar', 'iso2' => 'KI'],
            ['name' => 'Kuwait', 'code' => '+965', 'currency' => 'Kuwaiti Dinar', 'iso2' => 'KW'],
            ['name' => 'Kyrgyzstan', 'code' => '+996', 'currency' => 'Kyrgyzstani Som', 'iso2' => 'KG'],
            ['name' => 'Laos', 'code' => '+856', 'currency' => 'Lao Kip', 'iso2' => 'LA'],
            ['name' => 'Latvia', 'code' => '+371', 'currency' => 'Euro', 'iso2' => 'LV'],
            ['name' => 'Lebanon', 'code' => '+961', 'currency' => 'Lebanese Pound', 'iso2' => 'LB'],
            ['name' => 'Lesotho', 'code' => '+266', 'currency' => 'Lesotho Loti', 'iso2' => 'LS'],
            ['name' => 'Liberia', 'code' => '+231', 'currency' => 'Liberian Dollar', 'iso2' => 'LR'],
            ['name' => 'Libya', 'code' => '+218', 'currency' => 'Libyan Dinar', 'iso2' => 'LY'],
            ['name' => 'Liechtenstein', 'code' => '+423', 'currency' => 'Swiss Franc', 'iso2' => 'LI'],
            ['name' => 'Lithuania', 'code' => '+370', 'currency' => 'Euro', 'iso2' => 'LT'],
            ['name' => 'Luxembourg', 'code' => '+352', 'currency' => 'Euro', 'iso2' => 'LU'],
            ['name' => 'Malta', 'code' => '+356', 'currency' => 'Euro', 'iso2' => 'MT'],
            ['name' => 'Marshall Islands', 'code' => '+692', 'currency' => 'United States Dollar', 'iso2' => 'MH'],
            ['name' => 'Mauritania', 'code' => '+222', 'currency' => 'Mauritanian Ouguiya', 'iso2' => 'MR'],
            ['name' => 'Mauritius', 'code' => '+230', 'currency' => 'Mauritian Rupee', 'iso2' => 'MU'],
            ['name' => 'Mexico', 'code' => '+52', 'currency' => 'Mexican Peso', 'iso2' => 'MX'],
            ['name' => 'Micronesia', 'code' => '+691', 'currency' => 'United States Dollar', 'iso2' => 'FM'],
            ['name' => 'Moldova', 'code' => '+373', 'currency' => 'Moldovan Leu', 'iso2' => 'MD'],
            ['name' => 'Monaco', 'code' => '+377', 'currency' => 'Euro', 'iso2' => 'MC'],
            ['name' => 'Mongolia', 'code' => '+976', 'currency' => 'Mongolian Tögrög', 'iso2' => 'MN'],
            ['name' => 'Montenegro', 'code' => '+382', 'currency' => 'Euro', 'iso2' => 'ME'],
            ['name' => 'Morocco', 'code' => '+212', 'currency' => 'Moroccan Dirham', 'iso2' => 'MA'],
            ['name' => 'Mozambique', 'code' => '+258', 'currency' => 'Mozambican Metical', 'iso2' => 'MZ'],
            ['name' => 'Myanmar', 'code' => '+95', 'currency' => 'Burmese Kyat', 'iso2' => 'MM'],
            ['name' => 'Namibia', 'code' => '+264', 'currency' => 'Namibian Dollar', 'iso2' => 'NA'],
            ['name' => 'Nauru', 'code' => '+674', 'currency' => 'Australian Dollar', 'iso2' => 'NR'],
            ['name' => 'Nepal', 'code' => '+977', 'currency' => 'Nepalese Rupee', 'iso2' => 'NP'],
            ['name' => 'Netherlands', 'code' => '+31', 'currency' => 'Euro', 'iso2' => 'NL'],
            ['name' => 'New Zealand', 'code' => '+64', 'currency' => 'New Zealand Dollar', 'iso2' => 'NZ'],
            ['name' => 'Nicaragua', 'code' => '+505', 'currency' => 'Nicaraguan Córdoba', 'iso2' => 'NI'],
            ['name' => 'Niger', 'code' => '+227', 'currency' => 'West African CFA franc', 'iso2' => 'NE'],
            ['name' => 'Nigeria', 'code' => '+234', 'currency' => 'Nigerian Naira', 'iso2' => 'NG'],
            ['name' => 'North Korea', 'code' => '+850', 'currency' => 'North Korean Won', 'iso2' => 'KP'],
            ['name' => 'North Macedonia', 'code' => '+389', 'currency' => 'Macedonian Denar', 'iso2' => 'MK'],
            ['name' => 'Norway', 'code' => '+47', 'currency' => 'Norwegian Krone', 'iso2' => 'NO'],
            ['name' => 'Oman', 'code' => '+968', 'currency' => 'Omani Rial', 'iso2' => 'OM'],
            ['name' => 'Pakistan', 'code' => '+92', 'currency' => 'Pakistani Rupee', 'iso2' => 'PK'],
            ['name' => 'Palau', 'code' => '+680', 'currency' => 'United States Dollar', 'iso2' => 'PW'],
            ['name' => 'Palestine', 'code' => '+970', 'currency' => 'Israeli New Shekel', 'iso2' => 'PS'],
            ['name' => 'Panama', 'code' => '+507', 'currency' => 'Panamanian Balboa', 'iso2' => 'PA'],
            ['name' => 'Papua New Guinea', 'code' => '+675', 'currency' => 'Papua New Guinean Kina', 'iso2' => 'PG'],
            ['name' => 'Paraguay', 'code' => '+595', 'currency' => 'Paraguayan Guaraní', 'iso2' => 'PY'],
            ['name' => 'Peru', 'code' => '+51', 'currency' => 'Peruvian Sol', 'iso2' => 'PE'],
            ['name' => 'Philippines', 'code' => '+63', 'currency' => 'Philippine Peso', 'iso2' => 'PH'],
            ['name' => 'Poland', 'code' => '+48', 'currency' => 'Polish Złoty', 'iso2' => 'PL'],
            ['name' => 'Portugal', 'code' => '+351', 'currency' => 'Euro', 'iso2' => 'PT'],
            ['name' => 'Qatar', 'code' => '+974', 'currency' => 'Qatari Riyal', 'iso2' => 'QA'],
            ['name' => 'Romania', 'code' => '+40', 'currency' => 'Romanian Leu', 'iso2' => 'RO'],
            ['name' => 'Russia', 'code' => '+7', 'currency' => 'Russian Ruble', 'iso2' => 'RU'],
            ['name' => 'Rwanda', 'code' => '+250', 'currency' => 'Rwandan Franc', 'iso2' => 'RW'],
            ['name' => 'Saint Kitts and Nevis', 'code' => '+1 869', 'currency' => 'East Caribbean Dollar', 'iso2' => 'KN'],
            ['name' => 'Saint Lucia', 'code' => '+1 758', 'currency' => 'East Caribbean Dollar', 'iso2' => 'LC'],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => '+1 784', 'currency' => 'East Caribbean Dollar', 'iso2' => 'VC'],
            ['name' => 'Samoa', 'code' => '+685', 'currency' => 'Samoan Tala', 'iso2' => 'WS'],
            ['name' => 'San Marino', 'code' => '+378', 'currency' => 'Euro', 'iso2' => 'SM'],
            ['name' => 'Sao Tome and Principe', 'code' => '+239', 'currency' => 'São Tomé and Príncipe Dobra', 'iso2' => 'ST'],
            ['name' => 'Saudi Arabia', 'code' => '+966', 'currency' => 'Saudi Riyal', 'iso2' => 'SA'],
            ['name' => 'Senegal', 'code' => '+221', 'currency' => 'West African CFA franc', 'iso2' => 'SN'],
            ['name' => 'Serbia', 'code' => '+381', 'currency' => 'Serbian Dinar', 'iso2' => 'RS'],
            ['name' => 'Seychelles', 'code' => '+248', 'currency' => 'Seychellois Rupee', 'iso2' => 'SC'],
            ['name' => 'Sierra Leone', 'code' => '+232', 'currency' => 'Sierra Leonean Leone', 'iso2' => 'SL'],
            ['name' => 'Singapore', 'code' => '+65', 'currency' => 'Singapore Dollar', 'iso2' => 'SG'],
            ['name' => 'Slovakia', 'code' => '+421', 'currency' => 'Euro', 'iso2' => 'SK'],
            ['name' => 'Slovenia', 'code' => '+386', 'currency' => 'Euro', 'iso2' => 'SI'],
            ['name' => 'Solomon Islands', 'code' => '+677', 'currency' => 'Solomon Islands Dollar', 'iso2' => 'SB'],
            ['name' => 'Somalia', 'code' => '+252', 'currency' => 'Somali Shilling', 'iso2' => 'SO'],
            ['name' => 'South Africa', 'code' => '+27', 'currency' => 'South African Rand', 'iso2' => 'ZA'],
            ['name' => 'South Korea', 'code' => '+82', 'currency' => 'South Korean Won', 'iso2' => 'KR'],
            ['name' => 'South Sudan', 'code' => '+211', 'currency' => 'South Sudanese Pound', 'iso2' => 'SS'],
            ['name' => 'Spain', 'code' => '+34', 'currency' => 'Euro', 'iso2' => 'ES'],
            ['name' => 'Sri Lanka', 'code' => '+94', 'currency' => 'Sri Lankan Rupee', 'iso2' => 'LK'],
            ['name' => 'Sudan', 'code' => '+249', 'currency' => 'Sudanese Pound', 'iso2' => 'SD'],
            ['name' => 'Suriname', 'code' => '+597', 'currency' => 'Surinamese Dollar', 'iso2' => 'SR'],
            ['name' => 'Sweden', 'code' => '+46', 'currency' => 'Swedish Krona', 'iso2' => 'SE'],
            ['name' => 'Switzerland', 'code' => '+41', 'currency' => 'Swiss Franc', 'iso2' => 'CH'],
            ['name' => 'Syria', 'code' => '+963', 'currency' => 'Syrian Pound', 'iso2' => 'SY'],
            ['name' => 'Taiwan', 'code' => '+886', 'currency' => 'New Taiwan Dollar', 'iso2' => 'TW'],
            ['name' => 'Tajikistan', 'code' => '+992', 'currency' => 'Tajikistani Somoni', 'iso2' => 'TJ'],
            ['name' => 'Tanzania', 'code' => '+255', 'currency' => 'Tanzanian Shilling', 'iso2' => 'TZ'],
            ['name' => 'Thailand', 'code' => '+66', 'currency' => 'Thai Baht', 'iso2' => 'TH'],
            ['name' => 'Timor-Leste', 'code' => '+670', 'currency' => 'United States Dollar', 'iso2' => 'TL'],
            ['name' => 'Togo', 'code' => '+228', 'currency' => 'West African CFA franc', 'iso2' => 'TG'],
            ['name' => 'Tonga', 'code' => '+676', 'currency' => 'Tongan Paʻanga', 'iso2' => 'TO'],
            ['name' => 'Trinidad and Tobago', 'code' => '+1 868', 'currency' => 'Trinidad and Tobago Dollar', 'iso2' => 'TT'],
            ['name' => 'Tunisia', 'code' => '+216', 'currency' => 'Tunisian Dinar', 'iso2' => 'TN'],
            ['name' => 'Turkey', 'code' => '+90', 'currency' => 'Turkish Lira', 'iso2' => 'TR'],
            ['name' => 'Turkmenistan', 'code' => '+993', 'currency' => 'Turkmenistani Manat', 'iso2' => 'TM'],
            ['name' => 'Tuvalu', 'code' => '+688', 'currency' => 'Australian Dollar', 'iso2' => 'TV'],
            ['name' => 'Uganda', 'code' => '+256', 'currency' => 'Ugandan Shilling', 'iso2' => 'UG'],
            ['name' => 'Ukraine', 'code' => '+380', 'currency' => 'Ukrainian Hryvnia', 'iso2' => 'UA'],
            ['name' => 'United Arab Emirates', 'code' => '+971', 'currency' => 'UAE Dirham', 'iso2' => 'AE'],
            ['name' => 'United Kingdom', 'code' => '+44', 'currency' => 'Pound Sterling', 'iso2' => 'GB'],
            ['name' => 'United States', 'code' => '+1', 'currency' => 'US Dollar', 'iso2' => 'US'],
            ['name' => 'Uruguay', 'code' => '+598', 'currency' => 'Uruguayan Peso', 'iso2' => 'UY'],
            ['name' => 'Uzbekistan', 'code' => '+998', 'currency' => 'Uzbekistani Som', 'iso2' => 'UZ'],
            ['name' => 'Vanuatu', 'code' => '+678', 'currency' => 'Vanuatu Vatu', 'iso2' => 'VU'],
            ['name' => 'Vatican City', 'code' => '+379', 'currency' => 'Euro', 'iso2' => 'VA'],
            ['name' => 'Venezuela', 'code' => '+58', 'currency' => 'Venezuelan Bolívar', 'iso2' => 'VE'],
            ['name' => 'Vietnam', 'code' => '+84', 'currency' => 'Vietnamese đồng', 'iso2' => 'VN'],
            ['name' => 'Yemen', 'code' => '+967', 'currency' => 'Yemeni Rial', 'iso2' => 'YE'],
            ['name' => 'Zambia', 'code' => '+260', 'currency' => 'Zambian Kwacha', 'iso2' => 'ZM'],
            ['name' => 'Zimbabwe', 'code' => '+263', 'currency' => 'Zimbabwean Dollar', 'iso2' => 'ZW'],

        ];

        // Generate flag URL dynamically
        foreach ($countries as &$country) {
            $country['image'] = "https://flagcdn.com/w40/".strtolower($country['iso2']).".png";
        }

        DB::table('countries')->insert($countries);
    }
}
